#YML configuration to manage
#  Merge request from user
#  Release request

readers:
    - urn:github:1119686

docker:
  image: "ubuntu:12.10"
 
merge: # or "deploy" or "release"
  commanders:
    - LaurentTardif
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - "mvn clean test install"
 
release: # or "deploy" or "release"
  commanders:
    - LaurentTardif
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
 #   - maven version ----    
 #   - "git commit -am \"${tag}\""
    - "mvn clean test site:site install"
 